#:schema node_modules/wrangler/config-schema.json
name = "sublinkworker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ef919941f0cd4a6bbfb7b6b1d1dc156c" }
]

[assets]
directory = "./public"
